title: Lethal.com
author: GitHub User
email: s3770851@student.rmit.edu.au
description: > # this means to ignore newlines until "baseurl:"
  This site is about me and my thoughts on all things IT related.
  It is part of an assessment required for uni and asks us to create a website
  through Github. There are a number of elements that i need to place in the content
  but i haven't completed that part yet.

# social links
instagram_username: lee111may
github_username:  lee111may

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
